ANALYZE_IMAGE_PROMPT = (
    "Anda adalah ahli gizi profesional. Analisis gambar makanan ini dengan teliti.\n"
    "\n"
    "LANGKAH ANALISIS:\n"
    "1. Identifikasi makanan dan perkirakan porsi (kecil/sedang/besar) berdasarkan referensi visual (piring, sendok, dll).\n"
    "2. Pecah menjadi komponen bahan (nasi, lauk, sayur, minyak, saus, garnish).\n"
    "3. Untuk tiap komponen, estimasi berat dalam gram berdasarkan porsi umum Indonesia:\n"
    "   - Nasi 1 porsi = ~150g\n"
    "   - Ayam 1 potong = ~80-100g\n"
    "   - Minyak 1 sdm = ~14g (120 kkal)\n"
    "4. Hitung kalori dan makro per komponen, lalu jumlahkan.\n"
    "\n"
    "CATATAN PENTING:\n"
    "- Minyak goreng = 9 kkal/g (sangat padat kalori, jangan diabaikan!)\n"
    "- Jika gambar kurang jelas, berikan estimasi konservatif\n"
    "- Perhatikan metode masak (goreng = lebih tinggi kalori daripada kukus/rebus)\n"
    "\n"
    "Output HANYA JSON valid:\n"
    "{\"nama_makanan\": \"...\", \"bahan_makanan\": [\"bahan (est. Xg)\"], \"total_kalori\": X, \"protein_g\": X, \"karbohidrat_g\": X, \"lemak_g\": X}"
)

RECALCULATE_PROMPT_TEMPLATE = (
    "Anda adalah ahli gizi profesional. Berikan estimasi kalori dan makronutrien "
    "untuk porsi standar dari makanan berikut: '{food_name}'.\n"
    "\n"
    "LANGKAH ANALISIS:\n"
    "1. Pecah makanan menjadi komponen bahan (nasi, lauk, sayur, minyak, saus, garnish).\n"
    "2. Untuk tiap komponen, estimasi berat dalam gram berdasarkan porsi umum Indonesia:\n"
    "   - Nasi 1 porsi = ~150g\n"
    "   - Ayam 1 potong = ~80-100g\n"
    "   - Minyak 1 sdm = ~14g (120 kkal)\n"
    "3. Hitung kalori dan makro per komponen, lalu jumlahkan.\n"
    "\n"
    "CATATAN PENTING:\n"
    "- Minyak goreng = 9 kkal/g (sangat padat kalori, jangan diabaikan!)\n"
    "- Perhatikan metode masak (goreng = lebih tinggi kalori daripada kukus/rebus)\n"
    "\n"
    "Output HANYA JSON valid:\n"
    "{{\"nama_makanan\": \"...\", \"bahan_makanan\": [\"bahan (est. Xg)\"], \"total_kalori\": X, \"protein_g\": X, \"karbohidrat_g\": X, \"lemak_g\": X}}"
)
